# config/recommendations.yml
recommendations:
  allowed_protocols:
    - 200
    - 201
    - 202
    - 203
    - 204
    - 205
    - 206
    - 208
    - 209
    - 210
    - 214
    - 215
    - 217
    - 218
    - 219
    - 221
    - 222
    - 223
    - 224
    - 225
    - 226
    - 227
    - 231
